env: Breakout-v0
#env: BreakoutDeterministic-v4
episodes: 100000
log_interval: 200

transforms:
  - type: grayscale
  - type: stack
    k: 4
  - type: permute_and_normalize

model:
  size: 128
  encoder:
    type: conv
    size: 16
    shared: True