env: Pong-v0
episodes: 100000
log_interval: 100

transforms:
  - type: grayscale
  - type: stack
    k: 4
    dim: 0
  - type: normalize

model:
  size: 128
  encoder:
    type: conv
    size: 16
    shared: True